Add the ability to get association counts for generic routes
monarch-initiative/biolink-api pull request #231
Opened 2018-10-12 00:11 UTC by deepakunni3

Add ability to get association counts for:
- `/bioentity/<id>`
- `bioentity/<type>/<id>`

The response looks like so:
```
{
  "taxon": {
    "id": "NCBITaxon:9606",
    "label": "Homo sapiens"
  },
  "association_counts": {
    "gene": 79,
    "interaction": 58,
    "homolog": 51,
    "phenotype": 84,
    "anatomical entity": 20,
    "biological process": 14,
    "pathway": 6,
    "disease": 4,
    "publication": 32,
    "variant": 13
  },
  "xrefs": null,
  "description": null,
  "categories": [
    "gene",
    "sequence feature"
  ],
  "types": null,
  "synonyms": null,
  "deprecated": null,
  "replaced_by": null,
  "consider": null,
  "id": "HGNC:18603",
  "label": "COL25A1"
}
```

2018-10-12 00:17 UTC, deepakunni3 commented
Related to https://github.com/biolink/biolink-api/issues/168

2018-10-12 00:34 UTC, kshefchek commented
Looks great! For genes we'll also want the count of phenotypes linked to all orthologs, and diseases associated with orthologs.  If you're testing with our dev index these won't show up since a bad version of panther made it through.

2018-10-12 17:52 UTC, deepakunni3 commented
@kshefchek I guess that will have to be a separate Solr query, right? Just wondering if it can be done in a more efficient way.

2018-12-07 18:50 UTC, kshefchek commented
For stats via orthology, I think we could get the breakdown by type (gene, phenotype, disease, function) and for each type get the stats per taxon.  Or alternatively we could get the breakdown of taxon per relation.  The later would allow us to disambiguate gene-gene data (intereraction vs orthology) but is harder to process.

Example taxon per category:
https://solr.monarchinitiative.org/solr/golr/select/?defType=edismax&qt=standard&indent=on&wt=json&rows=0&start=0&fl=*,score&facet=true&facet.mincount=1&json.nl=arrarr&facet.limit=20&facet.method=enum&fq=subject_ortholog_closure:%22MGI:98297%22&q=*:*&stats=true&stats.field={!tag=piv1%20calcdistinct=true%20distinctValues=false}object&facet.pivot={!stats=piv1}object_category,subject_taxon,object&f.object.facet.limit=0

Taxon per relation:
https://solr.monarchinitiative.org/solr/golr/select/?defType=edismax&qt=standard&indent=on&wt=json&rows=0&start=0&fl=*,score&facet=true&facet.mincount=1&json.nl=arrarr&facet.limit=20&facet.method=enum&fq=subject_ortholog_closure:%22MGI:98297%22&q=*:*&stats=true&stats.field={!tag=piv1%20calcdistinct=true%20distinctValues=false}object&facet.pivot={!stats=piv1}relation_label,subject_taxon,object&f.object.facet.limit=0

The latter is more informative, but we would need to disambiguate things like has_phenotype (sometimes overloaded and used for gene-disease, disease-phenotype)

This call would include everything (type per taxa per relation) but takes longer to finish:
https://solr.monarchinitiative.org/solr/golr/select/?defType=edismax&qt=standard&indent=on&wt=json&rows=0&start=0&fl=*,score&facet=true&facet.mincount=1&json.nl=arrarr&facet.limit=20&facet.method=enum&fq=subject_ortholog_closure:%22MGI:98297%22&q=*:*&stats=true&stats.field={!tag=piv1%20calcdistinct=true%20distinctValues=false}object&facet.pivot={!stats=piv1}relation_label,subject_taxon,object_category,object&f.object.facet.limit=0

I think for now let's go with a simple call (eg [object per object_category](https://solr.monarchinitiative.org/solr/golr/select/?defType=edismax&qt=standard&indent=on&wt=json&rows=0&start=0&fl=*,score&facet=true&facet.mincount=1&json.nl=arrarr&facet.limit=20&facet.method=enum&fq=subject_ortholog_closure:%22MGI:98297%22&q=*:*&stats=true&stats.field={!tag=piv1%20calcdistinct=true%20distinctValues=false}object&facet.pivot={!stats=piv1}object_category,object&f.object.facet.limit=0)) and have a separate call for the more complex query.

2018-12-07 18:52 UTC, kshefchek requested changes

2018-12-07 18:52 UTC, kshefchek commented on biolink/api/bio/association_counts.py
> +        stats_field='{!tag=piv1 calcdistinct=true distinctValues=false}object'
Add f.object.facet.limit=0, this will result in a faster response

2018-12-07 18:52 UTC, kshefchek commented on biolink/api/bio/association_counts.py
> +        stats_field='{!tag=piv1 calcdistinct=true distinctValues=false}subject'
Add f.subject.facet.limit=0

2018-12-07 19:02 UTC, kshefchek commented on biolink/api/bio/association_counts.py
> +        stats_field='{!tag=piv1 calcdistinct=true distinctValues=false}object'
Disregard, I see now what you're doing

2019-01-24 01:22 UTC, deepakunni3 commented
Added counts for ortholog associations using suggestions made by @kshefchek 

New response looks like so:
```json
{
    "taxon": {
        "id": "NCBITaxon:9606",
        "label": "Homo sapiens"
    },
    "association_counts": {
        "interactions": 58,
        "homologs": 51,
        "phenotypes": 84,
        "anatomy": 20,
        "functions": 14,
        "pathways": 6,
        "diseases": 4,
        "publications": 32,
        "variants": 13,
        "ortholog-interactions": 104,
        "ortholog-anatomy": 24,
        "ortholog-functions": 17,
        "ortholog-phenotypes": 18,
        "ortholog-pathways": 6
    },
    "xrefs": null,
    "description": null,
    "categories": [
        "gene",
        "sequence feature"
    ],
    "types": null,
    "synonyms": null,
    "deprecated": null,
    "replaced_by": null,
    "consider": null,
    "id": "HGNC:18603",
    "label": "COL25A1"
}
```

2019-01-24 17:44 UTC, deepakunni3 commented
@kshefchek Could you take a look at this? I think all the necessary counts are being returned. Wanted to see if I am interpreting the counts properly.

**Note:** To get this to work you would have to use ontobio@master

2019-01-29 00:50 UTC, kshefchek approved these changes

2019-01-29 00:51 UTC, kshefchek commented
+1, thanks for adding this!

2019-01-29 01:09 UTC, deepakunni3 commented
Awesome! 👍

2019-01-29 01:09 UTC, merged